import Head from 'next/head'

const Home = () => {
    return (
        <div>
            <Head>
                <title>Getir</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"/>
            </Head>

            getir.com
        </div>
    )
}

export default Home;
